steps:
  - label: build Docker image
    command: gcloud docker -- build -t gcr.io/infolinks-gcr/deployster:${BUILDKITE_COMMIT} .
  - label: push Docker image to GCR
    command: gcloud docker -- push gcr.io/infolinks-gcr/deployster:${BUILDKITE_COMMIT}
