steps:

  - label: Test
    command:
      - echo "RUN coveralls" >> ./Dockerfile.test
      - docker build -e BUILDKITE -e BUILDKITE_JOB_ID -e BUILDKITE_BRANCH --file "${DEPLOYSTER_HOME}/Dockerfile.test" .

  - wait

  - label: Build & push Docker images
    command:
      - ./.buildkite/build.sh ${BUILDKITE_COMMIT}
