steps:

  - label: Test
    command:
      - echo "ARG COVERALLS_REPO_TOKEN" >> ./Dockerfile.test
      - echo "ARG BUILDKITE" >> ./Dockerfile.test
      - echo "ARG BUILDKITE_JOB_ID" >> ./Dockerfile.test
      - echo "ARG BUILDKITE_BRANCH" >> ./Dockerfile.test
      - echo "COPY .git /app/.git/" >> ./Dockerfile.test
      - echo "RUN coveralls" >> ./Dockerfile.test
      - sed -i 's/^\/\.git$//' .dockerignore
      - docker build --build-arg COVERALLS_REPO_TOKEN="${COVERALLS_REPO_TOKEN}"
                     --build-arg BUILDKITE="${BUILDKITE}"
                     --build-arg BUILDKITE_JOB_ID="${BUILDKITE_JOB_ID}"
                     --build-arg BUILDKITE_BRANCH="${BUILDKITE_BRANCH}"
                     --file ./Dockerfile.test
                     --tag infolinks/deployster:testing .

  - wait

  - label: Build & push Docker images
    command:
      - ./.buildkite/build.sh ${BUILDKITE_COMMIT}
