steps:

  - label: build & push Docker image
    command:
      - gcloud docker -- build --tag gcr.io/infolinks-gcr/deployster:${BUILDKITE_COMMIT} .
      - gcloud docker -- push gcr.io/infolinks-gcr/deployster:${BUILDKITE_COMMIT}
