steps:

  - label: build & push Docker image
    command:
      - ./.buildkite/build.sh
      - gcloud docker -- push gcr.io/infolinks-gcr/deployster-gcp-base:${BUILDKITE_COMMIT}
      - gcloud docker -- push gcr.io/infolinks-gcr/deployster-gcp-compute-address:${BUILDKITE_COMMIT}
      - gcloud docker -- push gcr.io/infolinks-gcr/deployster-gcp-project:${BUILDKITE_COMMIT}
