steps:

  - label: Test
    command:
      - echo "COPY .git /app/.git/" >> ./Dockerfile.test
      - echo "RUN coveralls" >> ./Dockerfile.test
      - sed -i 's/^\/\.git$//' .dockerignore
      - source ./.buildkite/test.sh

  - wait

  - label: Build & push Docker images
    command:
      - ./.buildkite/build.sh ${BUILDKITE_COMMIT}
