steps:

  - label: Test
    command:
      - echo "ARG COVERALLS_REPO_TOKEN" >> ./Dockerfile.test.centos
      - echo "ARG BUILDKITE" >> ./Dockerfile.test.centos
      - echo "ARG BUILDKITE_JOB_ID" >> ./Dockerfile.test.centos
      - echo "ARG BUILDKITE_BRANCH" >> ./Dockerfile.test.centos
      - echo "RUN coveralls" >> ./Dockerfile.test.centos
      - docker build --build-arg COVERALLS_REPO_TOKEN="${COVERALLS_REPO_TOKEN}"
                     --build-arg BUILDKITE="${BUILDKITE}"
                     --build-arg BUILDKITE_JOB_ID="${BUILDKITE_JOB_ID}"
                     --build-arg BUILDKITE_BRANCH="${BUILDKITE_BRANCH}"
                     --file ./Dockerfile.test.centos
                     --tag infolinks/deployster:testing .

  - wait

  - label: Build & push Docker images
    command:
      - ./.buildkite/build.sh ${BUILDKITE_COMMIT}
