steps:

  - label: Test
    command:
      # run tests
      - ./.buildkite/test.sh

      # report coverage to 'coveralls.io'
      - sed -i 's/^\/\.git$//' .dockerignore
      - docker build -q --file ./Dockerfile.coverall --tag infolinks/deployster:coverall .
      - echo docker run --env COVERALLS_REPO_TOKEN="${COVERALLS_REPO_TOKEN}"
                   --env BUILDKITE="${BUILDKITE}"
                   --env BUILDKITE_JOB_ID="${BUILDKITE_JOB_ID}"
                   --env BUILDKITE_BRANCH="${BUILDKITE_BRANCH}"
                   --tty infolinks/deployster:coverall

  - wait

  - label: Build & push Docker images
    command:
      - ./.buildkite/build.sh ${BUILDKITE_COMMIT}
