resources:

  config-namespace:
    type: infolinks/deployster-k8s-namespace:0.0.0
    dependencies:
      cluster: test-cluster
    config:
      manifest:
        metadata:
          name: config

  test-configmap:
    type: infolinks/deployster-k8s-configmap:0.0.0
    dependencies:
      namespace: config-namespace
    config:
      manifest:
        metadata:
          name: test-configmap
        data:
          key1: value1
          key2: value2

  test-secret:
    type: infolinks/deployster-k8s-secret:0.0.0
    dependencies:
      namespace: config-namespace
    config:
      manifest:
        metadata:
          name: test-secret
        data:
          key3: value3
          key4: value4
