plugs:
  gcloud:
    path: {{ gcloud_path }}
    read_only: false

resources:

  project:
    type: infolinks/deployster-gcp-project:0.0.0
    config:
      project_id: {{ gcp_project }}
      organization_id: {{ organization_id }}
      billing_account_id: {{ billing_account_id }}
      apis:
        enabled:
          - cloudapis.googleapis.com
          - compute.googleapis.com
          - container.googleapis.com
          - storage-component.googleapis.com

  cluster:
    type: infolinks/deployster-gcp-gke-cluster:0.0.0
    dependencies:
      project: project
    config:
      zone: {{ zone }}
      name: test
      description: Test cluster.
      version: 1.8.2-gke.0
      node_pools:
        - name: default
          min_size: 1
          max_size: 1
          preemptible: true

  cluster-admin-role:
    type: infolinks/deployster-k8s-rbac-role:0.0.0
    readonly: true
    dependencies:
      cluster: cluster
    config:
      manifest:
        metadata:
          name: cluster-admin
        rules:
          - apiGroups:
            - '*'
            resources:
            - '*'
            verbs:
            - '*'
          - nonResourceURLs:
            - '*'
            verbs:
            - '*'

  team-cluster-admins-binding:
    type: infolinks/deployster-k8s-rbac-role-binding:0.0.0
    dependencies:
      role: cluster-admin-role
    config:
      manifest:
        metadata:
          name: team-cluster-admins
        subjects:
          - kind: User
            name: {{ user_email }}

  namespace:
    type: infolinks/deployster-k8s-namespace:0.0.0
    dependencies:
      cluster: cluster
    config:
      manifest:
        metadata:
          name: config

  configmap:
    type: infolinks/deployster-k8s-configmap:0.0.0
    dependencies:
      namespace: namespace
    config:
      manifest:
        metadata:
          name: config1
        data:
          key1: value1
          key2: value2

  secret:
    type: infolinks/deployster-k8s-secret:0.0.0
    dependencies:
      namespace: namespace
    config:
      manifest:
        metadata:
          name: secret1
        data:
          key3: value3
          key4: value4
